# Generated by Django 3.2.19 on 2023-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='percipitation_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
