# Generated by Django 3.2.19 on 2023-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_auto_20231019_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='feels_like',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
